stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/pre_processing.py
    deps:
    - data/raw
    - src/pre_processing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/features
    - src/model_training.py
    params:
    - model_training.kernel
    - model_training.C
    - model_training.random_state
    outs:
    - models/svc_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/svc_model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/evaluation_metrics.json
